# backend/mentoring/urls.py
from django.urls import path

from .views import (
    hod_dashboard,
    hod_allocations,
    hod_proposals,
    hod_suggest,
    hod_assign,
    hod_auto_distribute,
    hod_decide_proposals,
    hod_remove_allocation,
    hod_mentor_detail,
    hod_history,
    hod_settings,
    hod_filter_options,
    hod_change_requests,
    hod_change_request_detail,
    hod_decide_change_request,
    staff_my_mentees,
    staff_student_detail,
    student_my_mentor,
    staff_conversations,
    staff_thread,
    staff_groups,
    staff_broadcast,
    staff_change_requests,
    staff_change_request_detail,
    staff_act_change_request,
    staff_my_change_requests,
    staff_withdraw_change_request,
    student_thread,
    student_announcements,
    student_change_request,
    student_withdraw_change_request,
)

urlpatterns = [
    # ================= HOD — MENTOR ALLOCATION =================
    path("mentoring/hod/dashboard/",        hod_dashboard),
    path("mentoring/hod/allocations/",      hod_allocations),
    path("mentoring/hod/proposals/",        hod_proposals),
    path("mentoring/hod/suggest/",          hod_suggest),
    path("mentoring/hod/assign/",           hod_assign),
    path("mentoring/hod/auto-distribute/",  hod_auto_distribute),
    path("mentoring/hod/decide-proposals/", hod_decide_proposals),
    path("mentoring/hod/allocations/<int:allocation_id>/remove/", hod_remove_allocation),
    path("mentoring/hod/mentors/<int:mentor_id>/", hod_mentor_detail),
    path("mentoring/hod/history/",          hod_history),
    path("mentoring/hod/settings/",         hod_settings),
    path("mentoring/hod/options/",          hod_filter_options),
    path("mentoring/hod/change-requests/",  hod_change_requests),
    path("mentoring/hod/change-requests/<int:request_id>/", hod_change_request_detail),
    path("mentoring/hod/change-requests/<int:request_id>/decide/", hod_decide_change_request),

    # ================= STAFF (MENTOR) =================
    path("mentoring/staff/my-mentees/",              staff_my_mentees),
    path("mentoring/staff/students/<int:student_id>/", staff_student_detail),
    path("mentoring/staff/messages/",                staff_conversations),
    path("mentoring/staff/messages/<int:student_id>/", staff_thread),
    path("mentoring/staff/groups/",                  staff_groups),
    path("mentoring/staff/broadcast/",               staff_broadcast),
    path("mentoring/staff/change-requests/",         staff_change_requests),
    path("mentoring/staff/change-requests/<int:request_id>/", staff_change_request_detail),
    path("mentoring/staff/change-requests/<int:request_id>/act/", staff_act_change_request),
    path("mentoring/staff/my-change-requests/",      staff_my_change_requests),
    path("mentoring/staff/my-change-requests/<int:request_id>/withdraw/",
         staff_withdraw_change_request),

    # ================= STUDENT =================
    path("mentoring/student/my-mentor/",             student_my_mentor),
    path("mentoring/student/messages/",              student_thread),
    path("mentoring/student/announcements/",         student_announcements),
    path("mentoring/student/change-request/",        student_change_request),
    path("mentoring/student/change-request/<int:request_id>/withdraw/",
         student_withdraw_change_request),
]