# Generated by Django 4.2.30 on 2026-06-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='announcement_type',
        ),
        migrations.AddField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('students', 'Students'), ('teachers', 'Teachers'), ('parents', 'Parents')], default='everyone', max_length=20),
        ),
    ]
