# Generated by Django 4.2.30 on 2026-07-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_announcement_announcement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('google', 'Google')], default='manual', max_length=10),
        ),
    ]
