# Generated by Django 6.0.4 on 2026-04-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_assignment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allowed_types',
            field=models.CharField(default='PDF,DOCX', max_length=200),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='assignment',
            name='reference_file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/references/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='target_group',
            field=models.CharField(default='All Students', max_length=100),
        ),
    ]
