# Generated by Django 4.2.30 on 2026-07-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planunit',
            name='period_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
