# Generated by Django 4.2.30 on 2026-06-29 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_yeartutor_yeartutor_unique_tutor_per_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0002_holiday_semester_alter_timeslot_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_approvals', to='courses.course')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_submissions', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_approvals', to='courses.year')),
            ],
            options={
                'ordering': ['-submitted_at', '-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='timetableapproval',
            constraint=models.UniqueConstraint(fields=('year', 'semester'), name='unique_timetable_approval_per_class'),
        ),
    ]
