# Generated by Django 4.2.30 on 2026-07-15 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0019_subject_department'),
        ('timetable', '0003_timetableapproval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('preferred_position', models.CharField(choices=[('any', 'Any period'), ('first', 'First period'), ('last', 'Last period'), ('first_last', 'First or last period'), ('before_lunch', 'Before lunch'), ('after_lunch', 'After lunch')], default='any', max_length=20)),
                ('prefer_consecutive', models.BooleanField(default=False)),
                ('colour', models.CharField(default='#94a3b8', help_text='Hex colour for the grid, e.g. #94a3b8', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('periods_per_week', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['activity__name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('kind', models.CharField(choices=[('classroom', 'Classroom'), ('lab', 'Lab'), ('seminar', 'Seminar hall')], default='classroom', max_length=12)),
                ('capacity', models.PositiveSmallIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='timetableentry',
            name='unique_entry_per_assignment_slot',
        ),
        migrations.AddField(
            model_name='timetableapproval',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='kind',
            field=models.CharField(choices=[('class', 'Class'), ('activity', 'Activity')], default='class', max_length=12),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='courses.teachingassignment'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(condition=models.Q(('assignment__isnull', False)), fields=('assignment', 'day_of_week', 'time_slot'), name='unique_entry_per_assignment_slot'),
        ),
        migrations.AddField(
            model_name='classactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_activities', to='timetable.activitytype'),
        ),
        migrations.AddField(
            model_name='classactivity',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classactivity',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_activities', to='courses.year'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='class_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.classactivity'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='timetable.room'),
        ),
        migrations.AddConstraint(
            model_name='classactivity',
            constraint=models.UniqueConstraint(fields=('activity', 'year', 'semester'), name='uniq_class_activity'),
        ),
    ]
