# Generated by Django 4.2.30 on 2026-08-07 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_user_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentoringSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_students_per_mentor', models.PositiveIntegerField(default=25)),
                ('band_a_min', models.FloatField(default=8.0)),
                ('band_b_min', models.FloatField(default=6.5)),
                ('require_all_bands', models.BooleanField(default=True)),
                ('route_via_advisor', models.BooleanField(default=True)),
                ('first_year_rule', models.CharField(choices=[('defer', 'Allocate only after semester 1 results'), ('band_b', 'Assign all first years band B')], default='defer', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_setting', to='users.department')),
            ],
            options={
                'verbose_name': 'Mentoring setting',
            },
        ),
        migrations.CreateModel(
            name='MentorAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('grade_band', models.CharField(blank=True, choices=[('A', 'Band A'), ('B', 'Band B'), ('C', 'Band C')], max_length=1)),
                ('cgpa_at_allocation', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting HOD approval'), ('active', 'Active'), ('closed', 'Closed'), ('rejected', 'Proposal rejected')], default='pending', max_length=10)),
                ('source', models.CharField(choices=[('advisor', 'Class advisor proposal'), ('hod', 'Assigned directly by the HOD'), ('auto', 'Auto-distributed'), ('request', 'Change request approved')], default='hod', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_allocations', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_allocations', to='users.department')),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='mentee_allocations', to=settings.AUTH_USER_MODEL)),
                ('previous_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_allocations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_allocations', to=settings.AUTH_USER_MODEL)),
                ('suggested_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['department', 'academic_year', 'status'], name='mentoring_m_departm_3b144d_idx'), models.Index(fields=['mentor', 'is_active'], name='mentoring_m_mentor__a9b273_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mentorallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'academic_year'), name='one_active_mentor_per_student_per_year'),
        ),
        migrations.AddConstraint(
            model_name='mentorallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student', 'academic_year'), name='one_pending_proposal_per_student_per_year'),
        ),
    ]
