# Generated by Django 4.2.30 on 2026-08-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_alter_mentorallocation_grade_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoringsetting',
            name='allocate_from_year',
            field=models.PositiveSmallIntegerField(choices=[(1, 'I Year onwards'), (2, 'II Year onwards'), (3, 'III Year onwards'), (4, 'IV Year only')], default=2),
        ),
        migrations.AlterField(
            model_name='mentoringsetting',
            name='first_year_rule',
            field=models.CharField(choices=[('defer', 'Allocate only after semester 1 results'), ('band_b', 'Assign all first years grade B')], default='defer', max_length=10),
        ),
    ]
