# Generated by Django 4.2.30 on 2026-08-10 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentoring', '0003_mentoringsetting_allocate_from_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('group_key', models.CharField(default='all', max_length=40)),
                ('group_label', models.CharField(blank=True, max_length=120)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.department')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='mentoringsetting',
            name='first_year_rule',
            field=models.CharField(choices=[('defer', 'Allocate only after semester 1 results'), ('band_b', 'Assign all first years band B')], default='defer', max_length=10),
        ),
        migrations.CreateModel(
            name='MentorBroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='mentoring.mentorbroadcast')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-broadcast__created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='mentorbroadcastrecipient',
            constraint=models.UniqueConstraint(fields=('broadcast', 'student'), name='one_row_per_student_per_broadcast'),
        ),
    ]
