# Generated by Django 4.2.30 on 2026-08-20 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_user_must_change_password'),
        ('mentoring', '0004_mentorbroadcast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('raised_role', models.CharField(choices=[('student', 'Raised by the student'), ('mentor', 'Raised by the mentor')], default='student', max_length=8)),
                ('reason', models.CharField(choices=[('timing', 'Free periods never match'), ('subject', 'Mentor works in a different subject area'), ('availability', 'Mentor has not been available'), ('language', 'Language preference'), ('comfort', 'Not comfortable with the current mentor'), ('gender', 'Prefer a mentor of a particular gender'), ('capacity', 'Mentor is carrying too many students'), ('leave', 'Mentor is going on long leave'), ('other', 'Other')], max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('advisor', 'With the class advisor'), ('hod', 'With the HOD'), ('approved', 'Approved — student moved'), ('rejected', 'Rejected by the HOD'), ('resolved', 'Resolved by the class advisor'), ('withdrawn', 'Withdrawn')], default='hod', max_length=10)),
                ('advisor_note', models.TextField(blank=True)),
                ('advisor_acted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_change_requests', to=settings.AUTH_USER_MODEL)),
                ('current_mentor', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_against', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_change_requests', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_change_requests', to='users.department')),
                ('new_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mentoring.mentorallocation')),
                ('new_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_change_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['department', 'academic_year', 'status'], name='mentoring_m_departm_e7c1ac_idx'), models.Index(fields=['advisor', 'status'], name='mentoring_m_advisor_ab06d3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mentorchangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('advisor', 'hod'))), fields=('student', 'academic_year'), name='one_open_change_request_per_student_per_year'),
        ),
    ]
