# Generated by Django 4.2.30 on 2026-08-31 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_conversationmessage_attachment_and_more'),
        ('users', '0014_user_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentoring', '0005_mentorchangerequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('academic_year', models.CharField(max_length=9)),
                ('number', models.PositiveSmallIntegerField()),
                ('is_closed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_teams', to='courses.course')),
                ('mentor', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_teams', to=settings.AUTH_USER_MODEL)),
                ('mentor_was_suggested', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('course', 'year', 'academic_year', 'number')},
            },
        ),
        migrations.CreateModel(
            name='MentorTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(blank=True, max_length=1)),
                ('is_extra', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='mentoring.mentorteam')),
            ],
            options={
                'unique_together': {('team', 'student')},
            },
        ),
        migrations.CreateModel(
            name='MentorRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('team_size', models.PositiveSmallIntegerField(default=3)),
                ('grade_mix', models.CharField(choices=[('abc', 'One A, one B, one C'), ('none', 'No grade rule')], default='abc', max_length=5)),
                ('fallback', models.CharField(choices=[('extra_member', 'Allow an extra student from another band'), ('leave_short', 'Leave those teams one short')], default='extra_member', max_length=14)),
                ('skip_last_year_mentors', models.BooleanField(default=True)),
                ('skip_class_advisors', models.BooleanField(default=False)),
                ('tiebreak_fewest_mentees', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_rules', to='users.department')),
            ],
            options={
                'unique_together': {('department', 'academic_year')},
            },
        ),
    ]
