# Generated by Django 4.2.30 on 2026-09-01 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_conversationmessage_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentoring', '0006_mentorteam_mentorteammember_mentorrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnplacedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('academic_year', models.CharField(max_length=9)),
                ('band', models.CharField(blank=True, max_length=1)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unplaced_students', to='courses.course')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='unplaced_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
