# Generated by Django 4.2.30 on 2026-06-15 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0014_parentmessage_fee_conversationmessage'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='semester_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-semester'],
            },
        ),
        migrations.CreateModel(
            name='ResultEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.IntegerField(default=100)),
                ('marks_obtained', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('is_pass', models.BooleanField(default=False)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='exams.semesterresult')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject')),
            ],
        ),
        migrations.AddConstraint(
            model_name='semesterresult',
            constraint=models.UniqueConstraint(fields=('student', 'semester'), name='unique_semester_result_per_student'),
        ),
        migrations.AddConstraint(
            model_name='resultentry',
            constraint=models.UniqueConstraint(fields=('result', 'subject'), name='unique_result_entry_per_subject'),
        ),
    ]
