# Generated by Django 4.2.30 on 2026-06-15 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_subject_code'),
        ('exams', '0002_semesterresult_resultentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('exam_date', models.DateField()),
                ('session', models.CharField(choices=[('FN', 'Forenoon'), ('AN', 'Afternoon')], default='FN', max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='courses.subject')),
            ],
            options={
                'ordering': ['exam_date', 'session'],
            },
        ),
        migrations.AddConstraint(
            model_name='examschedule',
            constraint=models.UniqueConstraint(fields=('subject', 'semester'), name='unique_exam_per_subject_semester'),
        ),
    ]
