# Generated by Django 4.2.30 on 2026-06-16 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_subject_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0003_examschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevaluationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending_review', 'Pending Review'), ('revised', 'Revised'), ('retained', 'Retained')], default='pending_payment', max_length=20)),
                ('original_marks', models.FloatField(blank=True, null=True)),
                ('revised_marks', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revaluation_requests', to='courses.fee')),
                ('result_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revaluation_requests', to='exams.resultentry')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='revaluation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='revaluationrequest',
            constraint=models.UniqueConstraint(fields=('student', 'result_entry'), name='unique_revaluation_per_entry'),
        ),
    ]
