# Generated by Django 4.2.30 on 2026-06-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_revaluationrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevaluationWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(unique=True)),
                ('is_open', models.BooleanField(default=False)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
