# Generated by Django 4.2.30 on 2026-06-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_materialfolder_studymaterial_folder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
    ]
