# Generated by Django 4.2.30 on 2026-06-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_parentmessage_fee_conversationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
