# Generated by Django 4.2.30 on 2026-06-23 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0015_subject_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_tutors', to='courses.course')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_years', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_tutors', to='courses.year')),
            ],
        ),
        migrations.AddConstraint(
            model_name='yeartutor',
            constraint=models.UniqueConstraint(fields=('year',), name='unique_tutor_per_year'),
        ),
    ]
