# Generated by Django 4.2.30 on 2026-07-01 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0016_yeartutor_yeartutor_unique_tutor_per_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectives', models.TextField(blank=True)),
                ('outcomes', models.TextField(blank=True)),
                ('syllabus', models.TextField(blank=True)),
                ('textbooks', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('prerequisites', models.TextField(blank=True)),
                ('regulation', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Verification'), ('verified', 'Verified')], default='draft', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='courses.subject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_profiles_edited', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_profiles_verified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
