# Generated by Django 4.2.30 on 2026-07-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_courseprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CourseProfile',
        ),
    ]
