# Generated by Django 4.2.30 on 2026-07-09 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_must_change_password'),
        ('courses', '0018_subject_credits_delete_courseprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='users.department'),
        ),
    ]
