# Generated by Django 4.2.30 on 2026-07-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_subject_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='weekly_hours',
            field=models.IntegerField(default=0),
        ),
    ]
