# Generated by Django 4.2.30 on 2026-07-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_subject_weekly_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
    ]
