# Generated by Django 4.2.30 on 2026-08-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_parentmessage_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='context',
            field=models.CharField(choices=[('mentor', 'Mentor and mentee'), ('advisor', 'Class advisor and student'), ('parent', 'Teacher and parent'), ('general', 'Uncategorised')], db_index=True, default='general', max_length=10),
        ),
    ]
