# Generated by Django 4.2.30 on 2026-08-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_conversationmessage_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='private_messages/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='attachment_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
