# Generated by Django 4.2.30 on 2026-06-24 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('category', models.CharField(choices=[('paper_presentation', 'Paper presentation'), ('seminar', 'Seminar / conference'), ('placement', 'Placement drive'), ('sports', 'Sports'), ('nss_ncc', 'NSS / NCC'), ('other', 'Other')], max_length=32)),
                ('reason', models.TextField()),
                ('proof', models.FileField(blank=True, null=True, upload_to='od_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('stage', models.CharField(choices=[('awaiting_tutor', 'Awaiting tutor'), ('awaiting_hod', 'Awaiting HOD'), ('closed', 'Closed')], default='awaiting_tutor', max_length=16)),
                ('tutor_remark', models.CharField(blank=True, max_length=255)),
                ('tutor_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hod_remark', models.CharField(blank=True, max_length=255)),
                ('hod_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hod_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='od_hod_reviews', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='od_requests', to=settings.AUTH_USER_MODEL)),
                ('tutor_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='od_tutor_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
