# Generated by Django 4.2.30 on 2026-09-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_odrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odrequest',
            name='stage',
            field=models.CharField(choices=[('awaiting_tutor', 'Awaiting class advisor'), ('awaiting_hod', 'Awaiting HOD'), ('closed', 'Closed')], default='awaiting_tutor', max_length=16),
        ),
    ]
