# Generated by Django 4.2.30 on 2026-09-15 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0003_alter_odrequest_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('casual', 'Casual leave'), ('medical', 'Medical leave'), ('on_duty', 'On duty (conference / FDP / workshop)'), ('compensatory', 'Compensatory leave'), ('other', 'Other')], max_length=16)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('session', models.CharField(choices=[('full', 'Full day'), ('forenoon', 'Forenoon'), ('afternoon', 'Afternoon')], default='full', max_length=10)),
                ('days', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('reason', models.TextField()),
                ('proof', models.FileField(blank=True, null=True, upload_to='staff_leave_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('hod_remark', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_leave_decisions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_leave_requests', to='users.department')),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_leave_to_review', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'from_date'], name='attendance__status_6da7da_idx'), models.Index(fields=['teacher', 'status'], name='attendance__teacher_f44123_idx')],
            },
        ),
    ]
