# Generated by Django 4.2.30 on 2026-09-22 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0004_staffleaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffleaverequest',
            name='backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_leave_covering', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffleaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('recorded', 'Recorded')], default='pending', max_length=12),
        ),
    ]
