# Generated by Django 6.1 on 2026-08-14 08:17

import classgroups.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0021_subject_is_elective'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('class', 'Class group'), ('subject', 'Subject group')], default='class', max_length=8)),
                ('academic_year', models.CharField(max_length=9)),
                ('announcement_only', models.BooleanField(default=False, help_text='On: only the teacher can post. Students read but cannot reply.')),
                ('students_can_message', models.BooleanField(default=True)),
                ('students_can_upload', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='courses.course')),
                ('teaching_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='courses.teachingassignment')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='courses.year')),
            ],
            options={
                'ordering': ['kind', 'course__name', 'year__year_number'],
            },
        ),
        migrations.CreateModel(
            name='ClassMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Message'), ('announcement', 'Announcement')], default='text', max_length=14)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=classgroups.models.group_upload_path)),
                ('attachment_name', models.CharField(blank=True, max_length=200)),
                ('attachment_size', models.PositiveIntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='classgroups.classgroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassMessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_marks', to='classgroups.classgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_read_marks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='classgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'class')), fields=('course', 'year', 'academic_year'), name='one_class_group_per_class_per_year'),
        ),
        migrations.AddConstraint(
            model_name='classgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'subject')), fields=('teaching_assignment', 'academic_year'), name='one_subject_group_per_assignment_per_year'),
        ),
        migrations.AddIndex(
            model_name='classmessage',
            index=models.Index(fields=['group', 'created_at'], name='classgroups_group_i_00610b_idx'),
        ),
        migrations.AddIndex(
            model_name='classmessage',
            index=models.Index(fields=['group', 'message_type'], name='classgroups_group_i_29a6f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='classmessageread',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='one_read_mark_per_user'),
        ),
    ]
