# Generated by Django 4.2.30 on 2026-08-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classgroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='students_can_upload',
            field=models.BooleanField(default=True),
        ),
    ]
