# Generated by Django 4.2.30 on 2026-09-03 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classgroups', '0002_alter_classgroup_students_can_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closes_at', models.DateTimeField()),
                ('closed_early', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassPollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='classgroups.classpoll')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='classmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Message'), ('announcement', 'Announcement'), ('poll', 'Poll'), ('event', 'Event')], default='text', max_length=14),
        ),
        migrations.CreateModel(
            name='ClassPollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='classgroups.classpolloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='classgroups.classpoll')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classpoll',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='classgroups.classmessage'),
        ),
        migrations.CreateModel(
            name='ClassEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='classgroups.classmessage')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='classpollvote',
            constraint=models.UniqueConstraint(fields=('poll', 'student'), name='one_vote_per_student_per_poll'),
        ),
    ]
