# Generated by Django 4.2.30 on 2026-06-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role_parentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batch_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
