# Generated by Django 4.2.30 on 2026-06-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_department_hod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('parent', 'Parent'), ('accounts_admin', 'Accounts Admin'), ('exam_admin', 'Examination Admin'), ('academic_admin', 'Academic Admin')], default='student', max_length=30),
        ),
    ]
