# Generated by Django 4.2.30 on 2026-06-30 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('parent', 'Parent'), ('accounts_admin', 'Accounts Admin'), ('exam_admin', 'Examination Admin'), ('academic_admin', 'Academic Admin'), ('iqac_admin', 'IQAC Admin')], default='student', max_length=30),
        ),
        migrations.CreateModel(
            name='FacultyParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fdp', 'FDP / Training Attended'), ('workshop_attended', 'Workshop / Seminar Attended'), ('workshop_conducted', 'Workshop / Seminar Conducted'), ('conference', 'Conference Paper Presented'), ('journal', 'Journal Publication'), ('certification', 'Certification / MOOC (NPTEL etc.)'), ('guest_lecture', 'Guest Lecture Delivered'), ('committee', 'Committee / Cell Membership'), ('project', 'Project / Grant / Consultancy'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('organizer', models.CharField(blank=True, max_length=255)),
                ('activity_role', models.CharField(choices=[('attended', 'Attended'), ('conducted', 'Conducted / Organized'), ('presented', 'Presented'), ('published', 'Published'), ('member', 'Member'), ('other', 'Other')], default='attended', max_length=20)),
                ('date', models.DateField()),
                ('academic_year', models.CharField(blank=True, max_length=9)),
                ('proof', models.FileField(blank=True, null=True, upload_to='faculty_proofs/')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
